# Generated by Django 5.0.4 on 2024-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='AthmaCoin',
            field=models.IntegerField(default=0),
        ),
    ]
