# Generated by Django 5.0.4 on 2024-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.IntegerField(choices=[(0, 'not claimed'), (1, 'claimed')], default=0),
        ),
    ]
